# Generated by Django 6.0.3 on 2026-04-26 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_completedexercise_hero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255, verbose_name='Назва вправи')),
                ('xp_gained', models.IntegerField(verbose_name='Отримано XP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активність користувача',
                'verbose_name_plural': 'Історія активностей',
                'ordering': ['-created_at'],
            },
        ),
    ]
