# Generated by Django 6.0.3 on 2026-04-26 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_achievement_userachievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва предмета')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.IntegerField(default=100, verbose_name='Ціна (Fire Points)')),
                ('strength_bonus', models.IntegerField(default=0, verbose_name='Бонус до сили')),
                ('hp_bonus', models.IntegerField(default=0, verbose_name="Бонус до здоров'я")),
                ('icon', models.CharField(default='🛡️', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.item')),
            ],
            options={
                'verbose_name': 'Інвентар',
                'verbose_name_plural': 'Інвентарі користувачів',
            },
        ),
    ]
