# Generated by Django 6.0.3 on 2026-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team_profile_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='body_type',
            field=models.CharField(choices=[('NORMAL', 'Звичайний'), ('MUSCULAR', 'Накачений'), ('PLUMP', 'Пухлий')], default='NORMAL', max_length=20, verbose_name='Тип тіла'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image_url',
            field=models.CharField(default='image_11.png', max_length=255, verbose_name='Назва файлу картинки'),
        ),
    ]
