# Generated by Django 6.0.3 on 2026-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hero_body_type_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_skin',
            field=models.BooleanField(default=False, verbose_name='Це скін (костюм)?'),
        ),
        migrations.AddField(
            model_name='item',
            name='skin_image_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Файл скіна (напр. image_1.png)'),
        ),
    ]
